# Website details
name: Matt Metzgar
description: Blogging
email: email@site.com
author: author
lang: en
locale: en_US
logo: assets/img/logo.png

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: America/New_York
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: ""

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"

 